### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by haesleinhuepf** [WhoIsJack/CodingClubMiniTutorials#2]
Hi @WhoIsJack ,

that's a fantastic repository! I was just wondering under which conditions one could reuse the code and materials provided here. Would you mind adding a license file? If you're new to licensing and/or wonder which license to use, you can read more in this blob post: https://focalplane.biologists.com/2023/05/06/if-you-license-it-itll-be-harder-to-steal-it-why-we-should-license-our-work/

Thanks!

Best,
Robert

**Comment by WhoIsJack** [comment]
Hi Robert,

> that's a fantastic repository!

A debatable claim given its age and the slapdash nature of those Coding Club sessions from back in the day. These are tutorials for n00bs by a n00b; please bear that in mind when repurposing material.

MIT license added. Closing.

Cheers,
Jonas

**Comment by haesleinhuepf** [comment]
Amazing, thanks for the light speed response!
